const { faker } = require('@faker-js/faker');

/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
exports.seed = async function(knex) {
  // Deletes ALL existing entries
  await knex('characters').truncate();
  let data = [
    {
      'character_name': 'Orthur',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 1,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'J-Tron',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 2,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Bethany',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 3,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Ronan',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 4,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Tsarra',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 5,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Baloroth',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 6,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Rahu',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 7,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Chimney',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 8,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Ethan',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 9,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Mohandas',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 10,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Ozul',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 11,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Rye',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 12,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Onnophris',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 13,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Dex',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 14,
      'coin': 10,
      'premium_currency': 20,
    },
    {
      'character_name': 'Balor',
      'default_avatar': faker.image.imageUrl(),
      'winner_avatar': faker.image.imageUrl(),
      'default_speed': 20,
      'default_passing': 30,
      'default_stamina': 40,
      'default_shooting': 50,
      'default_tackling': 60,
      'superpower_id': 15,
      'coin': 10,
      'premium_currency': 20,
    },
  ];
  await knex('characters').insert([
    ...data
  ]);
  console.log('done game seeder')
};
